### ISSUE TITLE
Map PDS User stories with known usage of LLM

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/llms-and-pds#1]
## 💡 Description

Inputs are the user stories collected for the web design and litterature on LLM models.

**Comment by jordanpadams** [comment]
Trade study being tracked here: https://docs.google.com/spreadsheets/d/1O5rAJC8W2ff4RThE8UIZlAogWpBjF8SP/edit?usp=sharing&rtpof=true&sd=true

**Comment by AmandaMichelleR** [comment]
Updated Version of Trade Study/User Analysis/Grounded Theory on Excel:

https://jpl365prod-my.sharepoint.com/:x:/g/personal/amanda_robinson_jpl_nasa_gov/EXF_mVFhTMZKtCQoCQcn6BEBbxr54RxgvHWdu5I8uKCdQA?e=MLsvre
