### ISSUE TITLE
Create Embeddings/Vectors Using Wiki2Vec

### ISSUE THREAD

**Issue by AmandaMichelleR** [NASA-PDS/llms-and-pds#2]
Intern is instructed to look at the Pre-Embedding Model of Wiki2Vec
https://wikipedia2vec.github.io/wikipedia2vec/pretrained/

**Comment by jordanpadams** [comment]
Working on comparison of models

**Comment by tloubrieu-jpl** [comment]
Closed, what can be fixed from Amanda work has been fixed.
