### ISSUE TITLE
Look into Pre-trained Embedding Models & Calculate Cosine Similarity of Search Terms

### ISSUE THREAD

**Issue by AmandaMichelleR** [NASA-PDS/llms-and-pds#7]
Following Models:

- [ ] FastText
- [x] Universal Sentence Encoder
- [x] Glove
- [x] Wiki2Vec
- [x] Word2Vec
- [ ] Instructor Embedding
- [ ] Tiktoken

Etc.

**Comment by nutjob4life** [comment]
Able to tokenize XML data into sentences and words; working with GPT2 and "hugging face" transformer library. By this sprint it's hoped to demo the different models.

**Comment by jordanpadams** [comment]
research completed for this iteration. new ticket created for follow-on research, if needed
