### ISSUE TITLE
GPT2 Cosine Similarity & Collections Search

### ISSUE THREAD

**Issue by AmandaMichelleR** [NASA-PDS/llms-and-pds#9]
Use the transformer GPT2 model to get embeddings for labels and get cosine similarity of search terms. Once the model is functional, will attempt to compute embeddings for a collections search on PDS data.

**Comment by nutjob4life** [comment]
@AmandaMichelleR tokenizing through HuggingFace transformer; converting into Tensors, then into embeddings, then cosine similarities into embeddings in XML labels. Doing best! 🎉

**Comment by tloubrieu-jpl** [comment]
Closed, what can be fixed has been fixed for the short term needs.
